lib/mrkt/concerns/crud_leads.rb
According to http://developers.marketo.com/documentation/rest/createupdate-leads/ , the createupdate_leads endpoint has an optional parameter "asyncProcessing" that determines whether or not the endpoint returns immediately. I added support for it, defaulting to nil when not specified.
=> Added support for asyncProcessing param to createupdate_leads()

README.md, lib/mrkt.rb, lib/mrkt/concerns/crud_campaigns.rb, lib/mrkt/concerns/crud_helpers.rb, lib/mrkt/concerns/crud_leads.rb, spec/concerns/crud_campaigns_spec.rb
This PR adds the functionality to trigger a Smart Campaign for certain leads.
This accesses Marketo's the "Request Campaign" endpoint: http://developers.marketo.com/documentation/rest/request-campaign/
From the documentation of the API:
> This API runs an existing Marketo lead in a Marketo Smart Campaign. The
> Smart Campaign must have a “Campaign is Requested” trigger with a Web
> Service API source.
Usage:
```ruby
campaign_id = 42        # this is the ID of the campaign
lead_ids    = [1, 2, 4] # these are the leads who receive the campaign
tokens      = [{        # these tokens (optional) are then passed to the campaign
name:  '{{my.message}}',
value: 'Updated message'
}, {
name:  '{{my.other token}}',
value: 'Value for other token'
}]
client.request_campaign(campaign_id, lead_ids, …
```
=> Add request campaign feature – CrudCampaigns#request_campaign

lib/mrkt.rb, lib/mrkt/concerns/crud_lists.rb, spec/concerns/crud_lists_spec.rb
This PR adds support for two endpoints in the Marketo API. The [Get Leads by List](http://developers.marketo.com/documentation/rest/get-multiple-leads-by-list-id/) and [Add Leads to List](http://developers.marketo.com/documentation/rest/add-leads-to-list/) endpoints.
=> Crud Lists API - Get Leads by List, Add Leads to List

README.md
```
[1] pry(main)> response = client.get_leads(:email, 'takuyan@example.com')
NoMethodError: undefined method `join' for "takuyan@example.com":String
from /Users/takuyan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mrkt-0.6.1/lib/mrkt/concerns/crud_leads.rb:6:in `get_leads'
```
```
[2] pry(main)> response = client.get_leads(:email, ['takuyan@example.com'])
=> {:requestId=>"17b86#153509999ad",
:result=>
[{:id=>9999372,
:updatedAt=>"2016-03-07T06:24:12Z",
:lastName=>nil,
:email=>"takuyan@example.com",
:createdAt=>"2016-02-02T09:17:04Z",
:firstName=>nil}],
:success=>true}
```
=> docs: fix client.get_leads arguments from string to array

README.md, lib/mrkt.rb, lib/mrkt/concerns/authentication.rb, lib/mrkt/concerns/connection.rb, spec/concerns/authentication_spec.rb, spec/support/initialized_client.rb
This allows you to pass in a custom logger, which is passed on to Faraday. It also allows you to specify ```@debug``` when initializing the client instead of having to set it after the client is created. The ```@log_options``` parameter is so you can specify e.g. ```{bodies: true}```; if left nil then Faraday will complain so the default passed on is an empty hash ```{}```
=> Pass through logging options and retry_authentication

lib/mrkt.rb, lib/mrkt/concerns/crud_activities.rb, lib/mrkt/concerns/crud_custom_activities.rb, spec/concerns/crud_activities_spec.rb
Adding CRUD activities methods from http://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/.  This is only a subset of the available methods.
=> CRUD activities

lib/mrkt.rb, lib/mrkt/concerns/import_custom_objects.rb, spec/concerns/import_custom_objects_spec.rb
Adds bulk custom object import functionality. In addition to creating the job, you are able to poll the status and retrieve warnings/failures.
For reference: [custom object import documentation](http://developers.marketo.com/rest-api/bulk-import/bulk-custom-object-import/)
Question: Should be bump the version from `0.7.0` to `0.7.1`?
=> Add ability to bulk import custom objects

lib/mrkt/concerns/crud_activities.rb, spec/concerns/crud_activities_spec.rb
Hi! 👋 
This PR will implements `client.get_deleted_leads` as specified in [documentation](http://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Activities/getDeletedLeadsUsingGET)
=> Add client.get_deleted_leads

lib/mrkt/concerns/crud_lists.rb, spec/concerns/crud_lists_spec.rb
Hi @raszi, 
Thanks for maintaining this gem. This is the first of a couple tiny PRs that I hope to open.
This simply implements `remove_leads_from_list` according to the [documentation](http://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Static_Lists/removeLeadsFromListUsingDELETE)
=> feat(lists): add remove_leads_from_list to crud_lists

lib/mrkt.rb, lib/mrkt/concerns/crud_asset_static_lists.rb, lib/mrkt/errors.rb, spec/concerns/crud_asset_static_lists_spec.rb
Howdy again @raszi,
This implements:
- [`create_static_list`](http://developers.marketo.com/rest-api/endpoint-reference/asset-endpoint-reference/#!/Static_Lists/createStaticListUsingPOST)
- [`get_static_list_by_id`](http://developers.marketo.com/rest-api/endpoint-reference/asset-endpoint-reference/#!/Static_Lists/getStaticListByIdUsingGET)
- [`get_static_list_by_name`](http://developers.marketo.com/rest-api/endpoint-reference/asset-endpoint-reference/#!/Static_Lists/getStaticListByNameUsingGET)
- [`delete_static_list`](http://developers.marketo.com/rest-api/endpoint-reference/asset-endpoint-reference/#!/Static_Lists/deleteStaticListByIdUsingPOST)
=> feat(static lists): add initial CRUD for asset static lists

lib/mrkt.rb, lib/mrkt/concerns/crud_asset_folders.rb, spec/concerns/crud_asset_folders_spec.rb
Ok, this is the last one for a while. Obviously, let me know if you have any questions or feedback.
This implements:
- [`create_folder`](http://developers.marketo.com/rest-api/endpoint-reference/asset-endpoint-reference/#!/Folders/createFolderUsingPOST)
- [`get_folder_by_id`](http://developers.marketo.com/rest-api/endpoint-reference/asset-endpoint-reference/#!/Folders/getFolderByIdUsingGET)
- [`get_folder_by_name`](http://developers.marketo.com/rest-api/endpoint-reference/asset-endpoint-reference/#!/Folders/getFolderByNameUsingGET)
- [`delete_folder`](http://developers.marketo.com/rest-api/endpoint-reference/asset-endpoint-reference/#!/Folders/deleteFolderUsingPOST)
_Note_: I chose not to accept an optional `type` for `delete_folder` since passing 'Program', which is supposed to be an …
=> feat(asset folders): add initial CRUD for asset folders

lib/mrkt/concerns/crud_asset_static_lists.rb, lib/mrkt/concerns/crud_leads.rb, spec/concerns/crud_asset_static_lists_spec.rb, spec/concerns/crud_leads_spec.rb
Adds two more easy endpoints for Leads since there was time. I don't suspect, I won't get a chance to do anymore any time soon. Thanks!
This implements:
- [get_lead_by_id](http://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Leads/getLeadByIdUsingGET)
- [describe_lead](http://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Leads/describeUsingGET_2)
=> Extend CRUD Leads

README.md, lib/mrkt.rb, lib/mrkt/concerns/authentication.rb, spec/concerns/authentication_spec.rb
Thanks for maintaining this repo, @raszi !
This PR adds the ability to specify an optional Marketo LaunchPoint `partner_id`, per [their documentation](https://developers.marketo.com/rest-api/endpoint-reference/authentication-endpoint-reference/#!/Identity/identityUsingGET) and [instructions](http://developers.marketo.com/support/Marketo_LaunchPoint_Technology_Partner_API_Key.pdf).
This requirement was not obvious to us during initial implementation - it may be fairly new. But it appears they're selectively enforcing inclusion of this ID in the auth call for tracking purposes now.
=> Add optional partner_id param to auth

Gemfile.lock, lib/mrkt/version.rb, mrkt.gemspec
Faraday released version 1.0.0 on Jan 1 2020. I updated the faraday and faraday_middleware dependencies, and bumped the mrkt version from 0.11.0 to 0.11.1. I ran tests with `bundle exec rspec` and everything looks good. 
Closes #52
=> Bump faraday + faraday_middleware version range

Gemfile.lock, mrkt.gemspec
Hi!
faraday_middleware is now using faraday 1.0.
I bumped the version, ran all the tests and everything looks fine.
Let me know if I missed something or if there is some more work to do on the PR.
Thanks.
=> Bump faraday and faraday_middleware to use version 1.0

.travis.yml, Gemfile.lock, mrkt.gemspec
- Fixed `required_ruby_version`. `~> 2.5` works only `2.x`
- Remove older bundler lock
- Testing 3.0.0
=> Support ruby 3.0.0

lib/mrkt/errors.rb
The error codes library is a bit stale, and it felt like it could use an update with the [latest codes expressed in Marketo](https://developers.marketo.com/rest-api/error-codes/) - any that are > 1014. Please let me know if this feels like a sensible addition to this library. Thank you for your work on this!
=> Add additional error field mappings.

lib/mrkt.rb, lib/mrkt/concerns/crud_program_members.rb, spec/concerns/crud_program_members_spec.rb
This PR adds another marketo model `program members` to the supported cru(d) operations.
The implemented methods correspond to the following marketo rest api endpoints:
- [create_update_program_members](https://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Program_Members/syncProgramMemberStatusUsingPOST)
- [get_program_members](https://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Program_Members/getProgramMembersUsingGET)
- [describe_program_members](https://developers.marketo.com/rest-api/endpoint-reference/lead-database-endpoint-reference/#!/Program_Members/describeProgramMemberUsingGET2)
The implementation follows the same patterns used to implement the leads crud methods.
=> feat: add program member create, update and list methods

.github/workflows/ruby.yml
Ruby latest version is v3.1, but CI is not running.
* Add ruby v3.1 to CI matrix.
* Chang ruby version to a string.
* `3.0` is interpreted as `3`. CI runs on the latest version of v3.
=> CI against Ruby v3.1

.github/workflows/ruby.yml
Its life ended on 2021-04-05.
This also adds Ruby 3.2 support to the test suite.
https://www.ruby-lang.org/en/downloads/branches/
=> chore: drop Ruby 2.5 support

.github/workflows/ruby.yml, .rubocop.yml, Gemfile.lock, gemfiles/faraday_1.gemfile, gemfiles/faraday_2.gemfile, lib/mrkt/concerns/connection.rb, lib/mrkt/faraday.rb, lib/mrkt/faraday_middleware/response.rb, mrkt.gemspec
`faraday_middleware` is deprecated, and does not support Faraday v2.
From v1.10.0, faraday is bundled json middleware, and this gem can support Faraday v2.
* Require Ruby: v2.6 or higer
* Faraday v2 required Ruby v2.6.
* ruby v2.5 is EOL in March 2021.
* Require Faraday v1.10 or higher
* backport json middleware from this version.
* ref. https://github.com/lostisland/faraday/pull/1400
* Require `faraday-multipart`
* From Faraday v2, multipart middleware have been moved to separate faraday-multipart gem.
* ref. https://github.com/lostisland/faraday/blob/v2.0.0/UPGRADING.md#bundled-middleware-moved-out
* Add CI matrix
* Run tests on both versions of Faraday.
=> Compatible Faraday v2
